### ISSUE TITLE
Plot time domain Mount Lua

### ISSUE THREAD

**Issue by dhamalakamal** [ubsuny/CP1-24-HW5#28]
I will be working on this, as assigned by Professor. #17 

Work on a single data analysis Jupyter notebook using functions from preparation.py that contain for each task below only one plot:

combined plot of cleaned up and raw data by using some combination of waveform modification (which should include padding, windowing, taking the FFT, removing noise, inverse FFT, and undoing the window+padding) of the CO2 data of the Mount Lua observatory in the time domain (1 member due Friday 2pm)

**Comment by laserlab** [comment]
So please keep #17 open and close this one. Also make a new milestone specific to your task and assign it to #17
