### ISSUE TITLE
zbpetersbuf is doing fft / inverse fft

### ISSUE THREAD

**Issue by zbpetersbuf** [ubsuny/CP1-24-HW5#3]
fft / inverse fft using numpy and calculating the actual frequency in useful units (due monday)

**Comment by zbpetersbuf** [comment]
So I think im making a function to plot the frequency data. But the selection of frequencies, does that come from a function I make or just by looking at the graph of the invfft?

**Comment by laserlab** [comment]
> So I think im making a function to plot the frequency data. But the selection of frequencies, does that come from a function I make or just by looking at the graph of the invfft?

Do not make a function to plot. Please follow the homework task!

- a function that uses numpy inside a module called `preparation.py`
- the function should assume as an input a pandas time series with the index being a datetime object and the data being the concentration of CO2
- a function that is calculating the actual frequency in useful units

so please focus on those tasks and not plotting. If you need some example data to see what your function should do take this:

```python
import pandas as pd
import numpy as np

data = pd.Series(np.sin(range(0,10)),index=range(0,10))
```

**Comment by zbpetersbuf** [comment]
1 so I have already did a couple things since I was unsure, should I delete the part that plots the inverse fft?
2 also should I include a read me or just a description in the modules where the function is located
3 also I was working on a unit test aswell should I delete this?

**Comment by laserlab** [comment]
So all functions you do need a docstring in the same file and a unit test in `test_preparation.py`

**Comment by zbpetersbuf** [comment]
so the index being a datetime object I would need to know what this looks like before I finish the pull request, since if its in pure seconds then I do nothing but if its in month, day, year, time then the function for finding frequency would look different

**Comment by laserlab** [comment]
> so the index being a datetime object I would need to know what this looks like before I finish the pull request, since if its in pure seconds then I do nothing but if its in month, day, year, time then the function for finding frequency would look different

That’s exactly the point. But since it is a datetime object you know what is is! so you can convert it e.g. in seconds.
