### ISSUE TITLE
Data Collection Parameters

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW5#31]
Starting a thread here so that we can set some specifics about the data scrape.

### 1) Monthly Averages or Discrete Measurements
First off, we have the option of using data from the [monthly averages ](https://gml.noaa.gov/aftp/data/trace_gases/ch4/flask/surface/txt/ch4_avi_surface-flask_1_ccgg_month.txt) or [discrete measurements](https://gml.noaa.gov/aftp/data/trace_gases/ch4/flask/surface/txt/ch4_avi_surface-flask_1_ccgg_event.txt).  

I would suggest we go with the monthly averages since the data is more consistent, but if we want a higher resolution in the data then using the set of discrete measurements would be better-- and of course we could always both.

### 2) Number and Distribution of Sites
Right now I have all of the site data (for methane), so we have a large degree of freedom over which sites/datasets we select. We need to follow the task prompt, but beyond that I am open to input regarding which sites to use.  

### 3) Metadata 
If there is any additional metadata that would be useful downstream, let me know and I'll include it.

Right now each testing site has the following metadata included:
```json
    {
        "Category": "Greenhouse Gases",
        "Frequency": "Monthly Averages",
        "Readme Link": "https://gml.noaa.gov//aftp/data/trace_gases/ch4/flask/surface/README_ch4_surface-flask_ccgg.html",
        "Elevation": "185.0",
        "Site Code": "ALT",
        "Latitude": "82.451",
        "Country": "Canada",
        "Data Link": "https://gml.noaa.gov//aftp/data/trace_gases/ch4/flask/surface/txt/ch4_alt_surface-flask_1_ccgg_month.txt",
        "Description": "Air samples collected in glass flasks.",
        "Site URL": "https://gml.noaa.gov//dv/site/index.php?stacode=ALT",
        "Location": "Alert, Nunavut, Canada",
        "Longitude": "-62.507",
        "Type": "Flask",
        "Name": "Methane(CH4)",
        "Year": "Multiple",
        "Timezone": "-5 hours"
    }
```
Before I ship the data, I can merge the metadata into each site's dataframe or I can provide it in a separate file. Whichever is more convenient for the data prep, just let me know.

If we don't need any of this, then I can just leave it behind!

**Comment by avgagliardo** [comment]
@kylemasc917 We should probably sync up our datasets with respect to 2)

**Comment by laserlab** [comment]
Great issue here! 
Regarding 1) We talked about it in class yesterday. We need equidistant and continuous data for the fft. Monthly is an edge case which we accept. So subsets (we only need a seasonal change) can also be used.
Also for multiple stations you want to find stations that have overlap in time

**Comment by kylemasc917** [comment]
I'm not sure each site I chose has methane data as well, but I think a few do.

**Comment by iglesias-cardinale** [comment]
My input was requested, but since my task is essentially just to extract and organize the data in a plottable way, I'm fine with whatever you guys decide on.

That being said, I agree that monthly average is a better solution for 1 since it'll provide smooth data and it seems that's what @haiderabbas007 went with in #26.

**Comment by zbpetersbuf** [comment]
So the Fourier series can't tell the difference when the entries of the data arnt evenly spaced. The data you would be collecting from the average per month wouldn't be evenly spaced. It would appear smoother since there are less data points, not because this method is more correct. Because even then you would be assuming that the period of this oscillation is purely yearly but we 'dont' know this because what if there's smaller oscillations monthly?

**Comment by avgagliardo** [comment]
Awesome feedback, thanks everyone!

 so what I think I am hearing is that want the discrete measurements for the better time resolution and that I can cross-reference against the sites that @kylemasc917 chose for his data, or supplement them with the next best option for any sites that do not have methane records.

**Comment by kylemasc917** [comment]
Yeah thats probably the best. I can post the stations I chose here if you want?

**Comment by avgagliardo** [comment]
Sure, if you have a list handy otherwise I can grab it from the data. Thanks!

**Comment by kylemasc917** [comment]
I apologize I've been having notification issues trying to keep my email from clogging up and didn't see this reply but for the sake of others my list is:

South America Data:

# site_code : USH
# site_name : Ushuaia
# site_country : Argentina

Oceania Data:

# site_code : CGO
# site_name : Cape Grim, Tasmania
# site_country : Australia

North America Data:

# site_code : UTA
# site_name : Wendover, Utah
# site_country : United States

Africa Data:

# site_code : ASK
# site_name : Assekrem
# site_country : Algeria

Asia Data:

# site_code : AMY
# site_name : Anmyeon-do
# site_country : Republic of Korea

Antarctica Data:

# site_code : PSA
# site_name : Palmer Station, Antarctica
# site_country : United States

Europe Data:

# site_code : ZEP
# site_name : Ny-Alesund, Svalbard
# site_country : Norway and Sweden

**Comment by avgagliardo** [comment]
> I apologize I've been having notification issues trying to keep my email from clogging up and didn't see this reply but for the sake of others my list is:
> 
> South America Data:
> 
> site_code : USH site_name : Ushuaia site_country : Argentina
> 
> Oceania Data:
> 
> site_code : CGO site_name : Cape Grim, Tasmania site_country : Australia
> 
> North America Data:
> 
> site_code : UTA site_name : Wendover, Utah site_country : United States
> 
> Africa Data:
> 
> site_code : ASK site_name : Assekrem site_country : Algeria
> 
> Asia Data:
> 
> site_code : AMY site_name : Anmyeon-do site_country : Republic of Korea
> 
> Antarctica Data:
> 
> site_code : PSA site_name : Palmer Station, Antarctica site_country : United States
> 
> Europe Data:
> 
> site_code : ZEP site_name : Ny-Alesund, Svalbard site_country : Norway and Sweden

No you are all good, thank you. I got it from your branch so I still owe you 👍
