### ISSUE TITLE
Write function to read json files and return pandas time series 

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW5#4]
I'll work on

- Function that reads in the json files from the data collection task and returns a pandas time series with the index being a datetime object and the data being the concentration of CO2 / methane (1 member due Wednesday 2pm)

**Comment by avgagliardo** [comment]
I might need some input in #31 regarding how you want to use the data in your task.

**Comment by iglesias-cardinale** [comment]
Closing as completed
